/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface MainFooter {
    }
    interface MainHeader {
    }
    interface PageBlog {
        "baseUrl": string;
    }
    interface SectionLoading {
    }
    interface SingleBlog {
        "baseUrl": string;
        "match": MatchResults;
    }
    interface TodoList {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMainFooterElement extends Components.MainFooter, HTMLStencilElement {
    }
    var HTMLMainFooterElement: {
        prototype: HTMLMainFooterElement;
        new (): HTMLMainFooterElement;
    };
    interface HTMLMainHeaderElement extends Components.MainHeader, HTMLStencilElement {
    }
    var HTMLMainHeaderElement: {
        prototype: HTMLMainHeaderElement;
        new (): HTMLMainHeaderElement;
    };
    interface HTMLPageBlogElement extends Components.PageBlog, HTMLStencilElement {
    }
    var HTMLPageBlogElement: {
        prototype: HTMLPageBlogElement;
        new (): HTMLPageBlogElement;
    };
    interface HTMLSectionLoadingElement extends Components.SectionLoading, HTMLStencilElement {
    }
    var HTMLSectionLoadingElement: {
        prototype: HTMLSectionLoadingElement;
        new (): HTMLSectionLoadingElement;
    };
    interface HTMLSingleBlogElement extends Components.SingleBlog, HTMLStencilElement {
    }
    var HTMLSingleBlogElement: {
        prototype: HTMLSingleBlogElement;
        new (): HTMLSingleBlogElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "main-footer": HTMLMainFooterElement;
        "main-header": HTMLMainHeaderElement;
        "page-blog": HTMLPageBlogElement;
        "section-loading": HTMLSectionLoadingElement;
        "single-blog": HTMLSingleBlogElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface MainFooter {
    }
    interface MainHeader {
    }
    interface PageBlog {
        "baseUrl"?: string;
    }
    interface SectionLoading {
    }
    interface SingleBlog {
        "baseUrl"?: string;
        "match"?: MatchResults;
    }
    interface TodoList {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "main-footer": MainFooter;
        "main-header": MainHeader;
        "page-blog": PageBlog;
        "section-loading": SectionLoading;
        "single-blog": SingleBlog;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "main-footer": LocalJSX.MainFooter & JSXBase.HTMLAttributes<HTMLMainFooterElement>;
            "main-header": LocalJSX.MainHeader & JSXBase.HTMLAttributes<HTMLMainHeaderElement>;
            "page-blog": LocalJSX.PageBlog & JSXBase.HTMLAttributes<HTMLPageBlogElement>;
            "section-loading": LocalJSX.SectionLoading & JSXBase.HTMLAttributes<HTMLSectionLoadingElement>;
            "single-blog": LocalJSX.SingleBlog & JSXBase.HTMLAttributes<HTMLSingleBlogElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
